### ISSUE TITLE
Google structured data corrections / fix schema.org errors

### ISSUE THREAD

**Issue by binjetztauchimnetz** [Xtendify/Simple-Calendar#154]
before:
`<span class="simcal-event-start simcal-event-start-time" data-event-start="1460563200" data-event-format="H:i" itemprop="startDate" data-content="2016-04-13T19:00:00+0300">19:00</span>`
after:
`<span class="simcal-event-start simcal-event-start-time" data-event-start="1460563200" data-event-format="H:i" itemprop="startDate" content="2016-04-13T19:00:00+0300">19:00</span>`

`data-content=` is not working anymore and events are no longer crawled due to errors below.

reproduce:
1.  [http://demo.simplecalendar.io/list-view](http://demo.simplecalendar.io/list-view/)
2. [in https://developers.google.com/structured-data/testing-tool](https://developers.google.com/structured-data/testing-tool?url=http%253A%252F%252Fdemo.simplecalendar.io%252Flist-view%252F&filter=EVENTS)
3. Errors: 
   location [Place]:
   address:    missing and required
   name:   missing and required
   startDate:  missing and required

fix: 
events-builder.php:714 `'itemprop="' . $bound . 'Date" data-content="' . $event_dt->toIso8601String() . '" content="' . $event_dt->toIso8601String() . '">'`

**Comment by nickyoung87** [comment]
@binjetztauchimnetz If you would like to make a PR for this I would be glad to look it over and get it added in.

**Comment by nickyoung87** [comment]
@pderksen I think this is the biggest one for 3.1.2. A few users asking about this now.

**Comment by nickyoung87** [comment]
Also a new ref: https://wordpress.org/support/topic/structured-data-testing-tool-6

**Comment by pderksen** [comment]
Ref: http://schema.org/Event

**Comment by pderksen** [comment]
- https://github.com/moonstonemedia/Simple-Calendar/commit/5aa5dc2ab6dc1da151e31d35f2c2adb5b57a92c6
- https://github.com/moonstonemedia/Simple-Calendar/commit/5aa5dc2ab6dc1da151e31d35f2c2adb5b57a92c6
- https://github.com/moonstonemedia/Simple-Calendar/commit/993bbe53e69bd687fd090d3d0dfd4eb4e8756b87

**Comment by pderksen** [comment]
Fixed. Tested on test sites & demo site, both list & grid views using https://developers.google.com/structured-data/testing-tool

**Comment by nickyoung87** [comment]
@pderksen Looks like there is still possibly an issue here: https://wordpress.org/support/topic/structured-data-testing-tool-6/#post-8179729

Will let you re-open as you see fit.

**Comment by fer-sd** [comment]
Hi @nickyoung87, is this issue already fixed? I am still getting errors on Google Search Console for both location and name (version 3.1.9). Thanks in advance!

**Comment by nickyoung87** [comment]
No this is not quite fixed yet. We tried making it better but there are still some things not working properly.

**Comment by fer-sd** [comment]
Thanks a lot @nickyoung87, please let us know when it is fixed. Next release maybe?

**Comment by nickyoung87** [comment]
@fer-sd Thanks for understanding. I honestly am not sure when this will get done for sure and I don't want to promise a date and potentially let down on that promise.

**Comment by gacharijohn** [comment]
Need to also look into missing Structured data fields as well such as;

-  image
-  performer
-  eventStatus
-  organizer
-  offers

Ref: https://wordpress.org/support/topic/structured-data-issues-reported-by-google-search-console/
